---
net_vlan_state: overridden
net_vlan_config:
  - name: Desktops4
    vlan_id: 5
  - name: Servers11
    vlan_id: 10
  - name: Dmz1
    vlan_id: 20
  - name: Printer1
    vlan_id: 444
  - name: boston1
    vlan_id: 1234
