---
net_vlan_state: overridden
net_vlan_config:
  - name: desktops1
    vlan_id: 5
  - name: servers1
    vlan_id: 10
  - name: dmzs1
    vlan_id: 20
  - name: feb7
    vlan_id: 333
  - name: chapelhill
    vlan_id: 444
  - name: boston
    vlan_id: 1234
